CREATE SEQUENCE seq_cart_id
    MINVALUE 1
    MAXVALUE 999
    INCREMENT BY 1
    START WITH 4
    NOCACHE
    NOCYCLE;
    
CREATE SEQUENCE seq_customer_id
    MINVALUE 0001
    MAXVALUE 99999
    INCREMENT BY 1
    START WITH 0001
    NOCACHE
    NOCYCLE;